FROM node:20.10.0-slim as builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run generate

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder /app/.output/public .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
